In [55]:
import pandas as pd
import numpy as np

In [56]:
data = pd.read_excel(r"C:\Users\mk744\Downloads\Payout Difference\Admitad FS 30.xlsx")
data.head()

,Inventory,Campaign_Name,Action Time,Amount,Status,Payout,Currency,Sub_Id,aa,bb,cc,ID
0,fsBlog,Flipkart [CPS] IN,2024-09-30 23:29:05,369,pending,9.33,INR,atrf,NaN,NaN,NaN,1085914065
1,fsBlog,Flipkart [CPS] IN,2024-09-30 23:29:04,699,pending,17.89,INR,app,productPage,not,login,1085913979
2,fsBlog,Flipkart [CPS] IN,2024-09-30 23:29:03,239,pending,8.48,INR,app,productPage,not,login,1085913842
3,fsBlog,Flipkart [CPS] IN,2024-09-30 23:29:03,781,pending,25.46,INR,store,page,NaN,NaN,1085913783
4,fsBlog,Flipkart [CPS] IN,2024-09-30 23:29:02,173,pending,4.25,INR,app,productPage,not,login,1085913656

In [57]:
Adm_cols = data.groupby(['Campaign_Name', 'Sub_Id', 'Currency']).agg(
                                              Total_Payout = ("Payout", lambda x : int(np.ceil(x.sum()))),
                                              Total_Sales = ("Payout", "count")
).reset_index().sort_values(by="Sub_Id", ascending=True)
Adm_cols['Date'] = "2024-09-30"
Adm_cols['Partner'] = "Admitad"
Adm_cols

,Campaign_Name,Sub_Id,Currency,Total_Payout,Total_Sales,Date,Partner
0,Flipkart [CPS] IN,aab,INR,254,10,2024-09-30,Admitad
1,Flipkart [CPS] IN,app,INR,3299,199,2024-09-30,Admitad
9,Myntra [CPS] IN,app,INR,563,10,2024-09-30,Admitad
12,Pepperfry Web [CPS] IN,app,INR,9,2,2024-09-30,Admitad
2,Flipkart [CPS] IN,atrf,INR,1771,28,2024-09-30,Admitad
14,ZipRecruiter US,atrf,USD,1,1,2024-09-30,Admitad
3,Flipkart [CPS] IN,csheetfsp,INR,0,1,2024-09-30,Admitad
4,Flipkart [CPS] IN,email,INR,19,2,2024-09-30,Admitad
5,Flipkart [CPS] IN,store,INR,952,49,2024-09-30,Admitad
15,ZipRecruiter US,tabm,USD,1,1,2024-09-30,Admitad
6,Flipkart [CPS] IN,telegram,INR,1327,100,2024-09-30,Admitad
8,Flipkart [CPS] IN - Influencer Partnerships,telegram,INR,39,2,2024-09-30,Admitad
10,Myntra [CPS] IN,telegram,INR,118,1,2024-09-30,Admitad
13,Pepperfry Web [CPS] IN,telegram,INR,4,1,2024-09-30,Admitad
7,Flipkart [CPS] IN,web,INR,64,4,2024-09-30,Admitad
11,Myntra [CPS] IN,web,INR,15,1,2024-09-30,Admitad

In [58]:
# Cuelinks 
Cuelinks = pd.read_excel(r"C:\Users\mk744\Downloads\Payout Difference\Cuelinks FS 30.xls")
Cuelinks

,Id,Campaign_Name,Payout,Status,Transaction Date,Sub_Id,c,a,b,Amount,Inventory
0,19695799,Gonoise,67.93,pending,2024-09-30,store,page,NaN,NaN,999.00,flipshope.com
1,19700233,GoDaddy,0.00,pending,2024-09-30,atrf,NaN,NaN,NaN,0.00,flipshope.com
2,19705181,Ajio,46.74,pending,2024-09-30,app,productPage,not,login,615.00,Flipkart telegram
3,19706223,Firstcry,25.50,pending,2024-09-30,store,page,NaN,NaN,3626.54,flipshope.com
4,19707078,Tata Cliq,35.06,pending,2024-09-30,store,page,NaN,NaN,1289.00,flipshope.com
5,19710399,GoDaddy,76.01,pending,2024-09-30,atrf,NaN,NaN,NaN,14.83,flipshope.com
6,19714829,GoDaddy,61.45,pending,2024-09-30,atrf,NaN,NaN,NaN,11.99,flipshope.com
7,19714830,GoDaddy,0.00,pending,2024-09-30,atrf,NaN,NaN,NaN,0.00,flipshope.com

In [59]:
Cuelinks_Cols = Cuelinks.groupby(['Campaign_Name', 'Sub_Id']).agg(
                                              Total_Payout = ("Payout", lambda x : int(np.ceil(x.sum()))),
                                              Total_Sales = ("Payout", "count")
).reset_index().sort_values(by="Sub_Id", ascending=True)
Cuelinks_Cols['Date'] = "2024-09-30"
Cuelinks_Cols['Partner'] = "Cuelinks"
Cuelinks_Cols['Currency'] = "INR"

In [60]:
Merge = pd.concat([Adm_cols, Cuelinks_Cols], ignore_index=True)
Merge.isna().sum()

Campaign_Name    0
Sub_Id           0
Currency         0
Total_Payout     0
Total_Sales      0
Date             0
Partner          0
dtype: int64

In [61]:
Merge

,Campaign_Name,Sub_Id,Currency,Total_Payout,Total_Sales,Date,Partner
0,Flipkart [CPS] IN,aab,INR,254,10,2024-09-30,Admitad
1,Flipkart [CPS] IN,app,INR,3299,199,2024-09-30,Admitad
2,Myntra [CPS] IN,app,INR,563,10,2024-09-30,Admitad
3,Pepperfry Web [CPS] IN,app,INR,9,2,2024-09-30,Admitad
4,Flipkart [CPS] IN,atrf,INR,1771,28,2024-09-30,Admitad
5,ZipRecruiter US,atrf,USD,1,1,2024-09-30,Admitad
6,Flipkart [CPS] IN,csheetfsp,INR,0,1,2024-09-30,Admitad
7,Flipkart [CPS] IN,email,INR,19,2,2024-09-30,Admitad
8,Flipkart [CPS] IN,store,INR,952,49,2024-09-30,Admitad
9,ZipRecruiter US,tabm,USD,1,1,2024-09-30,Admitad
10,Flipkart [CPS] IN,telegram,INR,1327,100,2024-09-30,Admitad
11,Flipkart [CPS] IN - Influencer Partnerships,telegram,INR,39,2,2024-09-30,Admitad
12,Myntra [CPS] IN,telegram,INR,118,1,2024-09-30,Admitad
13,Pepperfry Web [CPS] IN,telegram,INR,4,1,2024-09-30,Admitad
14,Flipkart [CPS] IN,web,INR,64,4,2024-09-30,Admitad
15,Myntra [CPS] IN,web,INR,15,1,2024-09-30,Admitad
16,Ajio,app,INR,47,1,2024-09-30,Cuelinks
17,GoDaddy,atrf,INR,138,4,2024-09-30,Cuelinks
18,Firstcry,store,INR,26,1,2024-09-30,Cuelinks
19,Gonoise,store,INR,68,1,2024-09-30,Cuelinks
20,Tata Cliq,store,INR,36,1,2024-09-30,Cuelinks

In [62]:
df = pd.read_csv(r"C:\Users\mk744\OneDrive - Poornima University\Desktop\python_tutorial\URL.csv")
df

                                                    url
0     https://flipshope.com/redirect/B0BSNNYHY5/2?so...
1     https://www.amazon.in/CrossBeats-Bluetooth-Cle...
2     https://flipshope.com/redirect/10181909/7?sour...
3     https://flipshope.com/redirect/10776230/7?sour...
4     https://www.amazon.in/dp/B01GRRYG9K?tag=flipsh...
...                                                 ...
6330  https://tsm.s3g6.com/click?url=https%3A%2F%2Fw...
6331  https://tsm.s3g6.com/click?url=https%3A%2F%2Fw...
6332  https://flipshope.com/redirect/B073XL19QZ/2?so...
6333    https://flipshope.com/redirect/443004538_blue/9
6334  https://whatsapp.com/channel/0029Va9w4dELSmbTU...

[6335 rows x 1 columns]

In [63]:
df.groupby('url').size().reset_index(name = 'count').sort_values(by = 'count', ascending=False)

                                                    url  count
2106                     https://t.me/flipshope_support     41
3742  https://whatsapp.com/channel/0029Va9w4dELSmbTU...     27
2104                     https://t.me/+ArFyVwSJ2xgyNWM1     13
1791  https://flipshope.com/redirect/MOBGBTHFRAUEZX6...      8
1899  https://flipshope.com/redirect/TAIGXZKPTN7NFZG...      7
...                                                 ...    ...
2024  https://linksredirect.com/?&url=https%3A%2F%2F...      1
2023  https://linksredirect.com/?&url=https%3A%2F%2F...      1
2022                              https://fs9.in/tzqcr6      1
2021                              https://fs9.in/ty9qza      1
5765                             https://www.zomato.com      1

[5766 rows x 2 columns]

In [64]:
df['url'].value_counts().reset_index(name='count')

                                                  index  count
0                        https://t.me/flipshope_support     41
1     https://whatsapp.com/channel/0029Va9w4dELSmbTU...     27
2                        https://t.me/+ArFyVwSJ2xgyNWM1     13
3     https://flipshope.com/redirect/MOBGBTHFRAUEZX6...      8
4                                 https://fs9.in/tl1qll      7
...                                                 ...    ...
5761  https://tsm.s3g6.com/click?url=https%3A%2F%2Fw...      1
5762  https://www.amazon.in/dp/B09H7216PF?tag=flipsh...      1
5763  https://flipshope.com/redirect/PLLG7CJZYW9YP7W...      1
5764  https://tsm.s3g6.com/click?url=https%3A%2F%2Fw...      1
5765    https://flipshope.com/redirect/443004538_blue/9      1

[5766 rows x 2 columns]

In [65]:
Ans = df[df['url'].str.contains('https://flipshope.com/redirect/MOBGBTHFRAUEZX6...')]
Ans

                                                    url
355   https://flipshope.com/redirect/MOBGBTHFRAUEZX6...
2427  https://flipshope.com/redirect/MOBGBTHFRAUEZX6...
2968  https://flipshope.com/redirect/MOBGBTHFRAUEZX6...
3671  https://flipshope.com/redirect/MOBGBTHFRAUEZX6...
4105  https://flipshope.com/redirect/MOBGBTHFRAUEZX6...
4187  https://flipshope.com/redirect/MOBGBTHFRAUEZX6...
4260  https://flipshope.com/redirect/MOBGBTHFRAUEZX6...
4339  https://flipshope.com/redirect/MOBGBTHFRAUEZX6...

In [66]:
import warnings
warnings.filterwarnings('ignore')
Ans['url'] = Ans['url'].astype('category')
Ans['url'].cat.categories

Index(['https://flipshope.com/redirect/MOBGBTHFRAUEZX6G/1?source=telegram'], dtype='object')

In [67]:
Ans['product_id'] = Ans['url'].str.split('/').str[4]
Ans['source'] = Ans['url'].str.split('source=').str[1]
Ans

,url,product_id,source
355,https://flipshope.com/redirect/MOBGBTHFRAUEZX6...,MOBGBTHFRAUEZX6G,telegram
2427,https://flipshope.com/redirect/MOBGBTHFRAUEZX6...,MOBGBTHFRAUEZX6G,telegram
2968,https://flipshope.com/redirect/MOBGBTHFRAUEZX6...,MOBGBTHFRAUEZX6G,telegram
3671,https://flipshope.com/redirect/MOBGBTHFRAUEZX6...,MOBGBTHFRAUEZX6G,telegram
4105,https://flipshope.com/redirect/MOBGBTHFRAUEZX6...,MOBGBTHFRAUEZX6G,telegram
4187,https://flipshope.com/redirect/MOBGBTHFRAUEZX6...,MOBGBTHFRAUEZX6G,telegram
4260,https://flipshope.com/redirect/MOBGBTHFRAUEZX6...,MOBGBTHFRAUEZX6G,telegram
4339,https://flipshope.com/redirect/MOBGBTHFRAUEZX6...,MOBGBTHFRAUEZX6G,telegram

In [68]:
ans = df[df['url'].str.contains('https://flipshope.com/redirect/TAIGXZKPTN7NFZG...')]
ans

                                                    url
2708  https://flipshope.com/redirect/TAIGXZKPTN7NFZG...
3365  https://flipshope.com/redirect/TAIGXZKPTN7NFZG...
4169  https://flipshope.com/redirect/TAIGXZKPTN7NFZG...
4199  https://flipshope.com/redirect/TAIGXZKPTN7NFZG...
4289  https://flipshope.com/redirect/TAIGXZKPTN7NFZG...
4392  https://flipshope.com/redirect/TAIGXZKPTN7NFZG...
5455  https://flipshope.com/redirect/TAIGXZKPTN7NFZG...

In [69]:
ans['url'] = ans['url'].astype('category')
ans['url'].cat.categories

Index(['https://flipshope.com/redirect/TAIGXZKPTN7NFZGG/1?source=telegram'], dtype='object')

In [70]:
Data = df[df['url'].str.contains('https://whatsapp.com/channel/0029Va9w4dELSmbTU...')]
Data

                                                    url
628   https://whatsapp.com/channel/0029Va9w4dELSmbTU...
728   https://whatsapp.com/channel/0029Va9w4dELSmbTU...
760   https://whatsapp.com/channel/0029Va9w4dELSmbTU...
776   https://whatsapp.com/channel/0029Va9w4dELSmbTU...
804   https://whatsapp.com/channel/0029Va9w4dELSmbTU...
869   https://whatsapp.com/channel/0029Va9w4dELSmbTU...
1028  https://whatsapp.com/channel/0029Va9w4dELSmbTU...
1043  https://whatsapp.com/channel/0029Va9w4dELSmbTU...
2354  https://whatsapp.com/channel/0029Va9w4dELSmbTU...
3056  https://whatsapp.com/channel/0029Va9w4dELSmbTU...
3749  https://whatsapp.com/channel/0029Va9w4dELSmbTU...
3770  https://whatsapp.com/channel/0029Va9w4dELSmbTU...
3800  https://whatsapp.com/channel/0029Va9w4dELSmbTU...
3929  https://whatsapp.com/channel/0029Va9w4dELSmbTU...
3996  https://whatsapp.com/channel/0029Va9w4dELSmbTU...
4205  https://whatsapp.com/channel/0029Va9w4dELSmbTU...
5215  https://whatsapp.com/channel/0029Va9w4dELSmbTU...
5228  https://whatsapp.com/channel/0029Va9w4dELSmbTU...
5366  https://whatsapp.com/channel/0029Va9w4dELSmbTU...
5501  https://whatsapp.com/channel/0029Va9w4dELSmbTU...
5569  https://whatsapp.com/channel/0029Va9w4dELSmbTU...
5661  https://whatsapp.com/channel/0029Va9w4dELSmbTU...
5786  https://whatsapp.com/channel/0029Va9w4dELSmbTU...
5861  https://whatsapp.com/channel/0029Va9w4dELSmbTU...
5927  https://whatsapp.com/channel/0029Va9w4dELSmbTU...
5931  https://whatsapp.com/channel/0029Va9w4dELSmbTU...
6334  https://whatsapp.com/channel/0029Va9w4dELSmbTU...

In [71]:
Data['url'] = Data['url'].astype('category')
Data['url'].cat.categories

Index(['https://whatsapp.com/channel/0029Va9w4dELSmbTUYc88G2j'], dtype='object')

In [72]:
vec = df[df['url'].str.contains('https://tsm.s3g6.com/')]
vec

                                                    url
18    https://tsm.s3g6.com/click?url=https%3A%2F%2Fw...
19    https://tsm.s3g6.com/click?url=https%3A%2F%2Fw...
26    https://tsm.s3g6.com/click?url=https%3A%2F%2Fw...
38    https://tsm.s3g6.com/click?url=https%3A%2F%2Fw...
51    https://tsm.s3g6.com/click?url=https%3A%2F%2Fw...
...                                                 ...
6315  https://tsm.s3g6.com/click?url=https%3A%2F%2Fw...
6316  https://tsm.s3g6.com/click?url=https%3A%2F%2Fw...
6324  https://tsm.s3g6.com/click?url=https%3A%2F%2Fw...
6330  https://tsm.s3g6.com/click?url=https%3A%2F%2Fw...
6331  https://tsm.s3g6.com/click?url=https%3A%2F%2Fw...

[1596 rows x 1 columns]

In [73]:
vec['url'] = vec['url'].astype('category')
vec['url'].cat.categories

Index(['https://tsm.s3g6.com/click?campaign_id=4&pub_id=99&p1=1696572133532&url=https%3A%2F%2Fwww.flipkart.com%2Faquire-extra-large-pvc-vinyl-sticker%2Fp%2Fitme4vr5zgpgyfud%3Fpid%3DETYG9TF235J4TKAJ',
       'https://tsm.s3g6.com/click?campaign_id=4&pub_id=99&p1=1696572372522&url=https%3A%2F%2Fwww.flipkart.com%2Faquire-extra-large-pvc-vinyl-sticker%2Fp%2Fitme4vr5zgpgyfud%3Fpid%3DKTAGH3FBTZQUKZUW',
       'https://tsm.s3g6.com/click?campaign_id=4&pub_id=99&p1=1696573260484&url=https%3A%2F%2Fwww.flipkart.com%2Faquire-extra-large-pvc-vinyl-sticker%2Fp%2Fitme4vr5zgpgyfud%3Fpid%3DSHOFD83JHEUYU4KN',
       'https://tsm.s3g6.com/click?campaign_id=4&pub_id=99&p1=1696574586945&url=https%3A%2F%2Fwww.flipkart.com%2Faquire-extra-large-pvc-vinyl-sticker%2Fp%2Fitme4vr5zgpgyfud%3Fpid%3DHOLFQGRF4GKYHHEU',
       'https://tsm.s3g6.com/click?campaign_id=4&pub_id=99&p1=1696576631556&url=https%3A%2F%2Fwww.flipkart.com%2Faquire-extra-large-pvc-vinyl-sticker%2Fp%2Fitme4vr5zgpgyfud%3Fpid%3DRAMF9X8XCAGGM3QZ',
       'https://tsm.s3g6.com/click?campaign_id=4&pub_id=99&p1=1696578700083&url=https%3A%2F%2Fwww.flipkart.com%2Faquire-extra-large-pvc-vinyl-sticker%2Fp%2Fitme4vr5zgpgyfud%3Fpid%3DSFFGGYHTNYKZG47G',
       'https://tsm.s3g6.com/click?campaign_id=4&pub_id=99&p1=1696583114425&url=https%3A%2F%2Fwww.flipkart.com%2Faquire-extra-large-pvc-vinyl-sticker%2Fp%2Fitme4vr5zgpgyfud%3Fpid%3DTROGC4KJZHWYSQYW',
       'https://tsm.s3g6.com/click?campaign_id=4&pub_id=99&p1=1696583185318&url=https%3A%2F%2Fwww.flipkart.com%2Faquire-extra-large-pvc-vinyl-sticker%2Fp%2Fitme4vr5zgpgyfud%3Fpid%3DHRBG3VWYFRWJXFNF',
       'https://tsm.s3g6.com/click?campaign_id=4&pub_id=99&p1=1696584606255&url=https%3A%2F%2Fwww.flipkart.com%2Faquire-extra-large-pvc-vinyl-sticker%2Fp%2Fitme4vr5zgpgyfud%3Fpid%3DWSLG69HFY3MTAUNH',
       'https://tsm.s3g6.com/click?campaign_id=4&pub_id=99&p1=1696584677025&url=https%3A%2F%2Fwww.flipkart.com%2Feveready-10-w-standard-b22-led-bulb%2Fp%2Fitm21a97394b2c7a%3Fpid%3DBLBGKQJVMKDYYYYF%26lid%3DLSTBLBGKQJVMKDYYYYFQKZIEU%26marketplace%3DFLIPKART%26store%3Djhg%2Fyqn%2Ffeb%26pageUID%3D1696584453151%26affid%3Drohanpouri%26affExtParam1%3DENKR20231006A637524759%26affExtParam2%3DENKR20231006A637524759',
       ...
       'https://tsm.s3g6.com/click?url=https%3A%2F%2Fwww.myntra.com%2Fwomens-western-wear%3Ff%3DBrand%253ATokyo%2BTalkies%26rf%3DDiscount%2BRange%253A70.0_100.0_70.0%2BTO%2B100.0%26sort%3Dprice_asc&campaign_id=8&pub_id=99&p1=telegram_m&source={click_id}&p2=1714468473264',
       'https://tsm.s3g6.com/click?url=https%3A%2F%2Fwww.myntra.com%2Fwomens-western-wear%3Ff%3DCategories%253ADresses%252CShirts%252CSweatshirts%252CTops%252CTrousers%252CTshirts%26rf%3DDiscount%2BRange%253A80.0_100.0_80.0%2BTO%2B100.0%26sort%3Dprice_asc&campaign_id=8&pub_id=99&p1=telegram_m_undefined&source={click_id}&p2=1719580796249',
       'https://tsm.s3g6.com/click?url=https%3A%2F%2Fwww.myntra.com%2Fwomens-western-wear%3Ff%3DCategories%253ADresses%26rf%3DDiscount%2520Range%253A70.0_100.0_70.0%2520TO%2520100.0%26sort%3Dprice_asc&campaign_id=8&pub_id=99&p1=telegram_m&source={click_id}&p2=1718715241451',
       'https://tsm.s3g6.com/click?url=https%3A%2F%2Fwww.myntra.com%2Fwomens-western-wear%3Ff%3DCategories%253ALeggings%26rf%3DDiscount%2520Range%253A70.0_100.0_70.0%2520TO%2520100.0%26sort%3Dprice_asc&campaign_id=8&pub_id=99&p1=telegram_m&source={click_id}&p2=1718715241459',
       'https://tsm.s3g6.com/click?url=https%3A%2F%2Fwww.myntra.com%2Fwomens-western-wear%3Ff%3DCategories%253ATops%26rf%3DDiscount%2520Range%253A70.0_100.0_70.0%2520TO%2520100.0%26sort%3Dprice_asc&campaign_id=8&pub_id=99&p1=telegram_m&source={click_id}&p2=1718715241455',
       'https://tsm.s3g6.com/click?url=https%3A%2F%2Fwww.myntra.com%2Fwomens-western-wear%3Ff%3DCategories%253ATrousers%26rf%3DDiscount%2520Range%253A70.0_100.0_70.0%2520TO%2520100.0%26sort%3Dprice_asc&campaign_id=8&pub_id=99&p1=telegram_m&source={click_id}&p2=1718715241462',
       'https://tsm.s3g6.com/click?url=https%3A%2F%2Fwww.myntra.com%2Fwomens-western-wear%3Ff%3DCategories%253ATshirts%26rf%3DDiscount%2520Range%253A70.0_100.0_70.0%2520TO%2520100.0%26sort%3Dprice_asc&campaign_id=8&pub_id=99&p1=telegram_m&source={click_id}&p2=1718715241457',
       'https://tsm.s3g6.com/click?url=https%3A%2F%2Fwww.myntra.com%2Fwomens-western-wear%3Frf%3DDiscount%2520Range%253A80.0_100.0_80.0%2520TO%2520100.0%26sort%3Dprice_asc&campaign_id=8&pub_id=99&p1=telegram_m&source={click_id}&p2=1717854553601',
       'https://tsm.s3g6.com/click?url=https%3A%2F%2Fwww.myntra.com%2Fwonderchef%3Ff%3DCategories%253AElectric%2BKettle%252CPan%252CTawa%26rawQuery%3DWonderchef%26rf%3DDiscount%2BRange%253A70.0_100.0_70.0%2BTO%2B100.0%26sort%3Ddiscount%26atgSessionId%3DXWXV9kUvL5Xah48gtCmRsZ_p5053940%26expires%3D1745453091%26signature%3DcP8nLJliLXpO5qBoBG81bs5ZdmGEHRTlFXjfwKjcMh0%26clickid%3DXWXV9kUvL5Xah48gtCmRsZ_p5053940%26af_siteid%3DWishlink%26af_xp%3Dcustom%26&campaign_id=8&pub_id=99&p1=telegram_m&source={click_id}&p2=1713897519206',
       'https://tsm.s3g6.com/click?url=https%3A%2F%2Fwww.myntra.com%2Fwoodand-footwear%3FrawQuery%3Dwoodand%2520footwear%26rf%3DDiscount%2520Range%253A70.0_100.0_70.0%2520TO%2520100.0%26sort%3Drecommended&campaign_id=8&pub_id=99&p1=telegram_m&source={click_id}&p2=1715687426902'],
      dtype='object', length=1596)

In [74]:
class QuickSort:
    
    def swap(self, arr, i, j):
        """
        Swap the elements at index i and j in the array.
        """
        temp = arr[i]
        arr[i] = arr[j]
        arr[j] = temp

    def partition(self, arr, start, end):
        """
        Partition the array around a pivot element.
        Pivot is selected as the first element (arr[start]).
        After partition, all elements smaller than the pivot will be on the left,
        and all elements greater than the pivot will be on the right.
        """
        pivot = arr[start]  # choose the first element as the pivot
        i = start  # pointer for the boundary of elements less than the pivot
        
        for j in range(start + 1, end + 1):
            if arr[j] <= pivot:
                i += 1  # move boundary to the right
                self.swap(arr, i, j)  # swap element at i with element at j
        
        self.swap(arr, i, start)  # place the pivot in the correct position
        return i  # return the index of the pivot

    def quicksort(self, arr, start, end):
        """
        The main recursive function to sort the array using the Quicksort algorithm.
        It recursively sorts the left and right partitions around the pivot element.
        """
        if start >= end:
            return  # base case: if the array has one or zero elements
        
        # Partition the array and get the pivot's index
        pivot_index = self.partition(arr, start, end)
        
        # Recursively sort elements before the pivot and after the pivot
        self.quicksort(arr, start, pivot_index - 1)  # left partition
        self.quicksort(arr, pivot_index + 1, end)    # right partition

    def print_array(self, arr):
        """
        Utility function to print the array.
        """
        print(" ".join(map(str, arr)))


# Example usage:
if __name__ == "__main__":
    arr = [5, 3, 8, 4, 2]  # example array to sort
    sorter = QuickSort()    # create an instance of the QuickSort class
    
    print("Original array:")
    sorter.print_array(arr)  # print original array
    
    sorter.quicksort(arr, 0, len(arr) - 1)  # call quicksort to sort the array
    
    print("Sorted array:")
    sorter.print_array(arr)  # print the sorted array

Original array:
5 3 8 4 2
Sorted array:
2 3 4 5 8